### ISSUE TITLE
Missing way to require Attribute while keeping this in dev dependencies

### ISSUE THREAD

**Issue by simPod** [icanhazstring/phpstan-readonly-property#1]
The issue I've found is that this phpstan extension should be required as a dev dependency but the Attribute should be exposed as non-dev code because one must import it before using.

```php
use Icanhazstring\PhpstanReadonlyPropertyExtension\Attribute\Readonly;
```

**Comment by icanhazstring** [comment]
This shouldn't be a problem, as imports of nonexisting classes will be ignored.
Also, defined attributes that are nonexistent are simply ignored by PHP.

So this should work if you just import this from your dev-dependency where you are running your static analysis anyway.
On production this should not be an issue.

**Comment by simPod** [comment]
I'll try it and report back if I have any further issues. Thanks!

**Comment by simPod** [comment]
There are some classes where phpstan crashes for me at https://github.com/icanhazstring/phpstan-readonly-property/blob/262a10035a4e17a4b1f5decddb3f507538c4999f/src/Rule/WritingToReadonlyAttributePropertiesRule.php#L78

I debugged it and it seems it's because of https://github.com/Roave/BetterReflection/issues/701. But except that, this lib is looking good.

**Comment by icanhazstring** [comment]
I noticed this on some things also, but couldn't pin that one down.
Thanks for link, ill keep an I out for that 👍

**Comment by icanhazstring** [comment]
@simPod I could fix the issue with the internal error from BetteReflection.
It is caused then it tries to access attributes of a property when there are none.

Tagged with 0.1.2
