### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by simPod** [icanhazstring/phpstan-readonly-property#6]
`readonly` is a token in php 8.1 so having attributes with same name cause parse error there.

WDYT about renaming the attribute to `IsReadonly` and tagging v0.2?

**Comment by icanhazstring** [comment]
I think this lib should be incompatible with 8.1 as readonly tag support was only as workaround to have it available with 8.0.

But having a migration would be nice 😉
So EG a rector script in it something.

**Comment by simPod** [comment]
That does not allow migrating to php 8.1 without replacing all attributes with it.

I always migrate large projects without making any changes to the code in order to isolate behaviour change caused by php bump. But that is not possible now as I'm required to replace these attributes with upgrade https://phpstan.org/r/e2ea266b-91d7-4a38-86d0-4c279342954d

**Comment by icanhazstring** [comment]
Ah good. Point.
So yes, changing it to IsReadonly makes sense to be able to upgrade and then progress. 👍
